### ISSUE TITLE
Info panel still in white. And Info tabs headers are not visible.

### ISSUE THREAD

**Issue by UniverseXXX** [SebDanielsson/Dark-Combustion#1]
Info panel still in white. And Info tabs headers are not visible. 
Thanks
![image](https://user-images.githubusercontent.com/7465472/69866848-251c5280-129d-11ea-8ae2-d142eefc7949.png)

**Comment by SebDanielsson** [comment]
> Info panel still in white. And Info tabs headers are not visible.
> Thanks
> ![image](https://user-images.githubusercontent.com/7465472/69866848-251c5280-129d-11ea-8ae2-d142eefc7949.png)

Totally forgot about that pane. I've now released a new version.
