### ISSUE TITLE
Favicon and CSS

### ISSUE THREAD

**Issue by SteffanCline** [SebDanielsson/dark-combustion#2]
While it may seem petty but, can you please restore the favicon? It really does help when you have many tabs open to spot Transmission. It was working with the non-dockerized Transmission. 

Additionally, I really like your UI over the default but some of the CSS needs a tweak. For example, if you edit a torrent in the list to change it's path, the color of the Apply button is so dark, it's easy to miss.
<img width="1534" alt="Screen Shot 2022-06-09 at 10 41 55 PM" src="https://user-images.githubusercontent.com/1323544/172998255-aa6171d2-3e07-4635-9fd4-4e1020861b90.png">
.

**Comment by SebDanielsson** [comment]
Hi, nice catch! ☺️

I'll try to troubleshoot why the favicon doesn't appear. One question. When running outside Docker. Did you use my dark theme there as well or did you use the light theme that I based this dark theme on?

Will also tweak the color of the apply button as soon as I find time👍

**Comment by SebDanielsson** [comment]
Some fixes in [v1.0.1](https://github.com/SebDanielsson/dark-combustion/releases/tag/v1.0.1).
Just pull the latest CSS file and two buttons should be lighter. I'll continue to troubleshoot the missing favicon.☺️

**Comment by SebDanielsson** [comment]
Unfortunately the issue with the missing favicon seems to be a bug with the combustion theme. It looks for a favicon at `https://yourdomain.com/favicon.ico` instead of `https://yourdomain.com/transmission/web/favicon.ico`. Please file an issue there instead.

Repo: https://github.com/Secretmapper/combustion
